### ISSUE TITLE
Bug: Can't use seeds 

### ISSUE THREAD

**Issue by ejkkan** [Leonardo-Interactive/leonardo-ts-sdk#44]
When using a seed number it is ignored by the api. It uses a random seed number instead.

**Comment by amorphic** [comment]
Note that `seed` is not yet supported by the REST API. That's why it is not referenced in the docs:

- https://github.com/Leonardo-Interactive/leonardo-ts-sdk/blob/main/docs/sdks/generation/README.md#creategeneration
- https://docs.leonardo.ai/reference/creategeneration

This parameter is on the Leonardo roadmap and will be added to the API soon!
